[build]
  command = "npm run build:mainnet"

[context.deploy-preview.environment]
  NEXT_PUBLIC_INFURA_ENDPOINT = "https://mainnet.infura.io/v3/271258014f524ad78089bafc31409e45"
  NEXT_PUBLIC_NETWORK = "mainnet"
  NEXT_PUBLIC_IPFS_GATEWAY="https://cdn.kleros.link"
  NEXT_PUBLIC_VOUCH_DB_URL="https://vouches.proofofhumanity.id"
  NEXT_PUBLIC_TESTING = "true"
  NEXT_PUBLIC_THEGRAPH_APIKEY = "8f8c9d6963f1245f102681e6cbec86da"
  NEXT_PUBLIC_SUBGRAPHID = "0xb2a33ae0e07fd2ca8dbde9545f6ce0b3234dc4e8-0"
  NEXT_PUBLIC_COURT_FUNCTIONS_URL= "https://kleros-api.netlify.app"

[context.production.environment]
  NEXT_PUBLIC_INFURA_ENDPOINT = "https://mainnet.infura.io/v3/76223180ca554cad9b16c8879ef4db76"
  NEXT_PUBLIC_NETWORK = "mainnet"
  NEXT_PUBLIC_IPFS_GATEWAY="https://cdn.kleros.link"
  NEXT_PUBLIC_VOUCH_DB_URL="https://vouches.proofofhumanity.id"
  NEXT_PUBLIC_TESTING = "false"
  NEXT_PUBLIC_THEGRAPH_APIKEY = "8f8c9d6963f1245f102681e6cbec86da"
  NEXT_PUBLIC_SUBGRAPHID = "0xb2a33ae0e07fd2ca8dbde9545f6ce0b3234dc4e8-0"
  NEXT_PUBLIC_COURT_FUNCTIONS_URL= "https://kleros-api.netlify.app"